teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
  - name: admins
    maintainers:
      - DeepakNemad
      - KambleSahil3
      - ajile-in
      - amitpadmani-awts
      - kkkulkarni
    members:
      - ankita-p17
  - name: mobile-sdk-committers
    maintainers:
      - tusharbhayani
  - name: mobile-sdk-maintainers
    maintainers:
      - sairanjit
  - name: aries-admin
    maintainers:
      - sairanjit
  - name: dev-team
    maintainers:
      - ajile-in
      - amitpadmani-awts
      - kkkulkarni
    members:
      - GHkrishna
      - RinkalBhojani
      - ankita-p17
      - bhavanakarwade
      - pranalidhanavade
      - sairanjit
      - shitrerohit
      - tipusinghaw
      - tusharbhayani
      - alokmore-awts
  - name: credo-controller-committers
    maintainers:
      - KambleSahil3
  - name: devops-team
    maintainers:
      - DeepakNemad
    members:
      - KambleSahil3
  - name: github-committers
    maintainers:
      - ajile-in
  - name: mediator-agent-committers
    maintainers:
      - KambleSahil3
  - name: mediator-agent-maintainers
    maintainers:
      - sairanjit
  - name: mobile-wallet-team
    maintainers:
      - ajile-in
      - amitpadmani-awts
    members:
      - ankita-p17
  - name: platform-maintainers
    maintainers:
      - ankita-p17
    members:
      - RinkalBhojani
  - name: qa-team
    maintainers:
      - DeepakNemad
      - ajile-in
    members:
      - sayali-chavan2396
  - name: security-managers
    maintainers:
      - DeepakNemad
      - ajile-in
      - kkkulkarni
    members:
      - ankita-p17
      - jwagantall
      - ryjones
      - sairanjit
      - tipusinghaw
  - name: testing-team
    maintainers:
      - ajile-in
      - amitpadmani-awts
      - kkkulkarni
    members:
      - sayali-chavan2396
  - name: tsc
    maintainers:
      - ajile-in
      - amitpadmani-awts
    members:
      - jacquesvb71
      - siddharthdigiyatra
      - RinkalBhojani
      - ankita-p17
      - kkkulkarni
      - shitrerohit
  - name: verifier-app-admins
    maintainers:
      - ankita-p17
    members:
  - name: verifier-app-committers
    maintainers:
      - bhavanakarwade
    members:
      - shitrerohit
      - tipusinghaw
  - name: verification-templates-admins
    maintainers:
      - sairanjit
repositories:
  - name: .github
    teams:
      admins: admin
      github-committers: write
      security-managers: read
    visibility: public
  - name: .github-private
    teams:
      admins: admin
      security-managers: read
    visibility: private
  - name: C4GT
    teams:
      admins: admin
      security-managers: read
    visibility: public
  - name: mobile-sdk
    teams:
      mobile-sdk-committers: write
      mobile-sdk-maintainers: maintain
      admins: admin
      security-managers: read
    visibility: public
  - name: mobile-wallet
    teams:
      mobile-sdk-committers: write
      mobile-sdk-maintainers: maintain
      admins: admin
      security-managers: read
    visibility: public
  - name: aries-akrida
    teams:
      aries-admin: admin
      security-managers: read
    visibility: public
  - name: credebl-aries-oca-bundles
    teams:
      aries-admin: admin
      dev-team: write
      security-managers: read
    visibility: public
  - name: credebl.github.io
    teams:
      admins: admin
      dev-team: write
      security-managers: read
    visibility: public
  - name: credo-controller
    teams:
      admins: admin
      credo-controller-committers: write
      dev-team: write
      security-managers: read
    visibility: public
  - name: docs
    teams:
      admins: admin
      security-managers: read
    visibility: public
  - name: governance
    teams:
      lf-staff: maintain
      security-managers: write
    visibility: public
  - name: mediator-agent
    teams:
      admins: admin
      dev-team: write
      mediator-agent-committers: write
      mediator-agent-maintainers: maintain
      security-managers: read
    visibility: public
  - name: platform
    teams:
      admins: admin
      dev-team: write
      devops-team: write
      platform-maintainers: maintain
      qa-team: write
      security-managers: read
    visibility: public
  - name: studio
    teams:
      admins: admin
      dev-team: write
      qa-team: write
      security-managers: read
    visibility: public
  - name: terraform-scripts
    teams:
      admins: admin
      devops-team: write
      security-managers: read
    visibility: public
  - name: trust-registry
    teams:
      admins: admin
      dev-team: read
      security-managers: read
    visibility: public
  - name: verification-templates
    teams:
      verification-templates-admins: admin
      security-managers: read
    visibility: public
  - name: webauthn-server
    teams:
      admins: admin
      dev-team: write
      security-managers: read
    visibility: public
